# Generated by Django 4.2.1 on 2023-06-04 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_lecturetranscript"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturetranscript",
            name="lecture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.lecture",
            ),
        ),
        migrations.AddField(
            model_name="lecturetranscript",
            name="transcript",
            field=models.FileField(blank=True, null=True, upload_to="transcripts/"),
        ),
    ]
