# Generated by Django 4.2.1 on 2023-06-04 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_lecturetranscript_lecture_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lecturetranscript",
            old_name="lecture_text",
            new_name="transcript_text",
        ),
    ]
