# Generated by Django 4.2.1 on 2023-06-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_rename_lecture_text_lecturetranscript_transcript_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="lecture_transcript",
            field=models.FileField(blank=True, null=True, upload_to="transcripts/"),
        ),
        migrations.DeleteModel(name="LectureTranscript",),
    ]
