# Generated by Django 4.2.1 on 2023-06-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_lecture_lecture_transcript_delete_lecturetranscript"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="transcript_embeddings",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lecture",
            name="transcript_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
