# Generated by Django 4.2.1 on 2023-06-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_message_is_deleted_user_questions_asked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
