# Generated by Django 4.2.1 on 2023-06-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_course_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="total_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
