# Generated by Django 4.2.1 on 2023-08-06 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_user_total_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="expenditure",
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=10),
        ),
    ]
