# Generated by Django 4.2.1 on 2023-08-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_lecture_date_alter_user_expenditure"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="assistants",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="course_image",
            field=models.ImageField(blank=True, null=True, upload_to="course_images"),
        ),
        migrations.AddField(
            model_name="course",
            name="term",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="lecture_pdf",
            field=models.FileField(null=True, upload_to="lectures/"),
        ),
    ]
