# Generated by Django 4.2.1 on 2023-08-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_course_assistants_course_course_image_course_term_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="total_tokens", new_name="completion_tokens",
        ),
        migrations.AddField(
            model_name="lecture",
            name="syllabus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="question_asked_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="course",
            name="assistants",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
