# Generated by Django 4.2.1 on 2023-08-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_rename_total_tokens_user_completion_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="total_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
