# Generated by Django 4.2.1 on 2023-08-20 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_user_total_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussionmessages",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="base.discussionmessages",
            ),
        ),
    ]
