# Generated by Django 4.2.1 on 2023-08-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_alter_course_course_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="practice_quiz",
            field=models.FileField(blank=True, null=True, upload_to="practice_quiz/"),
        ),
    ]
