# Generated by Django 4.2.1 on 2023-09-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_lecture_practice_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="description",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
