# Generated by Django 4.2.1 on 2023-09-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_alter_lecture_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="professor",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
