# Generated by Django 4.2.1 on 2023-12-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0027_alter_user_expenditure"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="relavant_pages",
            field=models.BooleanField(default=False),
        ),
    ]
