# Generated by Django 4.2.1 on 2023-12-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0028_user_relavant_pages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="relavant_pages", new_name="relavent_pages",
        ),
    ]
