# Generated by Django 4.2.1 on 2023-12-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0029_rename_relavant_pages_user_relavent_pages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="relavent_pages", new_name="relevant_pages",
        ),
    ]
