# Generated by Django 4.2.1 on 2024-01-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0031_slide_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="slides_text",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
