# Generated by Django 4.2.1 on 2024-01-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0032_lecture_slides_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
