# Generated by Django 4.2.1 on 2024-01-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0033_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="username",),
    ]
