# Generated by Django 4.2.1 on 2024-01-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0034_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="roster",
            field=models.TextField(blank=True, null=True),
        ),
    ]
